# Generated by Django 6.0.6 on 2026-06-21 12:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='store_categ_slug_3348ec_idx',
            old_name='store_categ_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='store_categ_gender_69635a_idx',
            old_name='store_categ_gender_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_status_0921d2_idx',
            old_name='store_produ_status_feat_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_status_414322_idx',
            old_name='store_produ_status_new_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='store_produ_categor_c5f89f_idx',
            old_name='store_produ_cat_status_idx',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to / subtracted from base price', max_digits=8),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='store_order_user_id_c9744e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='store_order_order_n_317f52_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_on_sale'], name='store_produ_status_20596f_idx'),
        ),
    ]
