# Generated by Django 6.0.6 on 2026-06-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_store_categ_slug_idx_store_categ_slug_3348ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Cached average rating — updated via signals', max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached approved review count — updated via signals'),
        ),
    ]
