services:
  web:
    build: .
    command: gunicorn tailstore.wsgi:application --workers 3 --bind 0.0.0.0:8000
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles
      - media_files:/app/media
    depends_on:
      - web